In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
dataset=pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [11]:
print(x)

[['France' 53.0 27471.0]
 ['Spain' 39.0 79572.0]
 ['Germany' 39.0 56717.0]
 ['Spain' 48.0 42489.0]
 ['Germany' 54.0 nan]
 ['France' 46.0 27331.0]
 ['Spain' nan 21653.0]
 ['France' 40.0 84874.0]
 ['Germany' 51.0 60289.0]
 ['France' 39.0 37432.0]]


In [12]:
print(y)

['Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3]= imputer.transform(x[:,1:3])

In [18]:
print(x)

[['France' 53.0 27471.0]
 ['Spain' 39.0 79572.0]
 ['Germany' 39.0 56717.0]
 ['Spain' 48.0 42489.0]
 ['Germany' 54.0 48647.555555555555]
 ['France' 46.0 27331.0]
 ['Spain' 45.44444444444444 21653.0]
 ['France' 40.0 84874.0]
 ['Germany' 51.0 60289.0]
 ['France' 39.0 37432.0]]


In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [21]:
print(x)

[[1.0 0.0 0.0 53.0 27471.0]
 [0.0 0.0 1.0 39.0 79572.0]
 [0.0 1.0 0.0 39.0 56717.0]
 [0.0 0.0 1.0 48.0 42489.0]
 [0.0 1.0 0.0 54.0 48647.555555555555]
 [1.0 0.0 0.0 46.0 27331.0]
 [0.0 0.0 1.0 45.44444444444444 21653.0]
 [1.0 0.0 0.0 40.0 84874.0]
 [0.0 1.0 0.0 51.0 60289.0]
 [1.0 0.0 0.0 39.0 37432.0]]


In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
print(y)

[1 0 0 0 1 1 0 1 1 1]


In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [25]:
print(x_train)

[[0.0 0.0 1.0 45.44444444444444 21653.0]
 [0.0 1.0 0.0 54.0 48647.555555555555]
 [1.0 0.0 0.0 53.0 27471.0]
 [0.0 0.0 1.0 48.0 42489.0]
 [0.0 0.0 1.0 39.0 79572.0]
 [1.0 0.0 0.0 40.0 84874.0]
 [0.0 1.0 0.0 51.0 60289.0]
 [1.0 0.0 0.0 46.0 27331.0]]


In [26]:
print(x_test)

[[0.0 1.0 0.0 39.0 56717.0]
 [1.0 0.0 0.0 39.0 37432.0]]


In [27]:
print(y_train)

[0 1 1 0 0 1 1 1]


In [28]:
print(y_test)

[0 1]


In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [31]:
print(x_train)

[[0.0 0.0 1.0 -0.3083536398570883 -1.2138784114142207]
 [0.0 1.0 0.0 1.3291105166253796 -0.017430177151538735]
 [1.0 0.0 0.0 1.137718602231325 -0.9560139760241109]
 [0.0 0.0 1.0 0.18075903026105167 -0.29038865964585925]
 [0.0 0.0 1.0 -1.5417681992854404 1.3531979435805828]
 [1.0 0.0 0.0 -1.3503762848913854 1.5881923121674444]
 [0.0 1.0 0.0 0.7549347734432157 0.4985400013964153]
 [1.0 0.0 0.0 -0.20202479852705765 -0.962219032908713]]


In [32]:
print(x_test)

[[0.0 1.0 0.0 39.00000000000001 56717.00000000001]
 [1.0 0.0 0.0 39.00000000000001 37432.00000000001]]
